# Generated by Django 5.2 on 2025-04-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50, verbose_name='Раздел')),
                ('task', models.TextField(verbose_name='Задача')),
                ('answer', models.IntegerField(verbose_name='Ответ')),
            ],
        ),
    ]
